### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alisonjoseph** [txrg/website#1]
[Sitemap notes ](https://docs.google.com/document/d/1LZVbNMkUH57spnehvvRy9JEb9kZlRrRwmjAka5qDPl0/edit#)

### Code 👩‍💻 
**Create Pages**
- [x] Blog (needs work still)
- [x] Homepage

**Create Templates**
- [x] Team
- [ ] Profile
- [ ] Event List
- [x] Page
- [x] Blog

**Create Components**
- [x] Header
- [x] Navigation
- [x] Footer
- [x] Sponsor
- [x] Event Preview
- [x] Article Preview (blog)
- [x] Page Preview
- [x] Profile Preview
- [ ] Team

**Homepage Tasks**
- [x] Display "featured" blogs
- [x] Display "featured" pages
- [x] Display "featured" profile/skater
- [x] Display events 
- [ ] Display Banner
- [x] Display Sponsors 

**To Do**
- [ ] Remove blog listing? Or figure out where in nav it fits. 
- [x] Add sass/organize stylesheets

### Design 🎨 
- [ ] Header
- [ ] Navigation
- [ ] Footer
- [ ] Homepage
- [ ] Sponsor list
- [ ] Team Page
- [ ] Profile Page (skater, official, photog etc)
- [ ] Page Template w/ sub nav
- [ ] Event list

### Contentful 🌏 
**Create Content Types**
- [x] Page
- [x] Profile
- [x] Event
- [x] Sponsor
- [ ] Banner
- [ ] Team

### Content 📝 
Add allll the content from [www.texasrollergirls.org](http://www.texasrollergirls.org/)

- [x] Add sass
